services:
    # PHP Service - ini adalah jantung aplikasi Laravel kita
    php:
        # Build container dari Dockerfile yang sudah kita buat
        build:
            context: ../SIU_Apps                          # Build context adalah current directory
            dockerfile: ../SIU_Apps/docker/php/Dockerfile   # Path ke Dockerfile kita
        container_name: laravel_php_sui_apps
        restart: unless-stopped               # Restart otomatis jika container crash
        working_dir: /var/www/html

        # Volume mapping memungkinkan sharing file antara host dan container
        # Ini sangat penting untuk development agar perubahan code langsung terlihat
        volumes:
            - ./:/var/www/html                                    # Mount source code
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini  # Mount PHP config

        # Networks memungkinkan containers berkomunikasi satu sama lain
        networks:
            - default_network

    # Nginx Service - web server dan reverse proxy
    nginx:
        # Menggunakan official Nginx image dengan Alpine Linux
        image: nginx:alpine
        container_name: laravel_nginx_sui_apps
        restart: unless-stopped

        # Port mapping - map port 8080 di host ke port 80 di container
        # Ini memungkinkan kita akses aplikasi via http://localhost:8080
        ports:
            - "8085:80"

        volumes:
            # Mount source code agar Nginx bisa serve static files
            - ./:/var/www/html
            # Mount konfigurasi Nginx yang sudah kita buat
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

        networks:
            - default_network

        # Nginx membutuhkan PHP container untuk memproses PHP files
        depends_on:
            - php

# Networks definition
# Bridge network memungkinkan containers berkomunikasi menggunakan nama service
networks:
    default_network:
        external: true

# Volumes definition untuk data persistence
# Named volumes ini dikelola oleh Docker dan persisten across container restarts
volumes:
    mysql_data:
        driver: local
