<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TahunAkademik extends Model
{
    protected $table = 'tahun_akademik';

    protected $fillable= [
        'takad',
        'priode',
        'tahun',
        'status'
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::saving(function (TahunAkademik $tahunAkademik){
            // Cek jika status diubah menjadi 'Y'
            if ($tahunAkademik->isDirty('status') && $tahunAkademik->status === 'Y') {
                // Set semua record lain yang statusnya 'Y' menjadi 'N'
                // Ini memastikan hanya record yang sedang disimpan yang akan aktif.
                self::where('id', '!=', $tahunAkademik->id)->where('status', 'Y')->update(['status' => 'N']);
            }
        });
    }

}
